-- phpMyAdmin SQL Dump
-- version 4.0.10.16
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jul 29, 2016 at 05:26 PM
-- Server version: 5.5.31-cll
-- PHP Version: 5.3.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `smit6766`
--

-- --------------------------------------------------------

--
-- Table structure for table `dvd_genre`
--

CREATE TABLE IF NOT EXISTS `dvd_genre` (
  `genre_Id` int(30) NOT NULL COMMENT 'PK',
  `genre` varchar(50) NOT NULL,
  PRIMARY KEY (`genre_Id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `dvd_genre`
--

INSERT INTO `dvd_genre` (`genre_Id`, `genre`) VALUES
(1, 'drama'),
(2, 'comedy'),
(3, 'sports'),
(4, 'music'),
(5, 'documentary'),
(6, 'action'),
(7, 'adventure'),
(8, 'science fiction'),
(9, 'historical'),
(10, 'romance');

-- --------------------------------------------------------

--
-- Table structure for table `dvd_info`
--

CREATE TABLE IF NOT EXISTS `dvd_info` (
  `dvd_Id` int(30) NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `genre_Id` int(30) NOT NULL COMMENT 'FK',
  `title` text NOT NULL,
  `year` int(4) NOT NULL,
  `rating` char(2) NOT NULL,
  `cost` decimal(5,0) NOT NULL,
  `description` text NOT NULL,
  `imageURL` text NOT NULL,
  PRIMARY KEY (`dvd_Id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=101 ;

--
-- Dumping data for table `dvd_info`
--

INSERT INTO `dvd_info` (`dvd_Id`, `genre_Id`, `title`, `year`, `rating`, `cost`, `description`, `imageURL`) VALUES
(1, 8, 'Avatar', 2009, 'PG', '22', 'On the lush alien world of Pandora live the Na''vi, beings who appear primitive but are highly evolved. Because the planet''s environment is poisonous, human/Na''vi hybrids, called Avatars, must link to human minds to allow for free movement on Pandora. Jake Sully (Sam Worthington), a paralyzed former Marine, becomes mobile again through one such Avatar and falls in love with a Na''vi woman (Zoe Saldana). As a bond with her grows, he is drawn into a battle for the survival of her world.', 'https://images-na.ssl-images-amazon.com/images/I/51wYAC4gG3L._AC_US160_.jpg'),
(2, 2, 'Maverick', 1997, 'PG', '15', 'This film update of the "Maverick" TV series finds the title cardsharp (Mel Gibson) hoping to join a poker contest with an impressive payoff. In order to enter, Maverick must first put up a large cash sum. He scams hopeful contestants Annabelle (Jodie Foster) and Angel (Alfred Molina) in a preliminary card game to win the money he needs, making enemies of both players. While trying to evade Annabelle and Angel, the crafty Maverick realizes a cunning marshal (James Garner) is also on his tail.', 'https://images-na.ssl-images-amazon.com/images/I/513qoEUIAoL._AC_US160_.jpg'),
(3, 9, 'Saving Private Ryan', 1998, 'R', '25', 'Captain John Miller (Tom Hanks) takes his men behind enemy lines to find Private James Ryan, whose three brothers have been killed in combat. Surrounded by the brutal realties of war, while searching for Ryan, each man embarks upon a personal journey and discovers their own strength to triumph over an uncertain future with honor, decency and courage.', 'https://images-na.ssl-images-amazon.com/images/I/41q18r2JSaL._AC_US160_.jpg'),
(4, 9, 'Schindlers List', 1993, 'R', '22', 'Businessman Oskar Schindler (Liam Neeson) arrives in Krakow in 1939, ready to make his fortune from World War II, which has just started. After joining the Nazi party primarily for political expediency, he staffs his factory with Jewish workers for similarly pragmatic reasons. When the SS begins exterminating Jews in the Krakow ghetto, Schindler arranges to have his workers protected to keep his factory in operation, but soon realizes that in so doing, he is also saving innocent lives.', 'https://images-na.ssl-images-amazon.com/images/I/51t-qoZOLlL._AC_US160_.jpg'),
(5, 8, 'The Martian', 2015, 'PG', '20', 'When astronauts blast off from the planet Mars, they leave behind Mark Watney (Matt Damon), presumed dead after a fierce storm. With only a meager amount of supplies, the stranded visitor must utilize his wits and spirit to find a way to survive on the hostile planet. Meanwhile, back on Earth, members of NASA and a team of international scientists work tirelessly to bring him home, while his crew mates hatch their own plan for a daring rescue mission.', 'https://images-na.ssl-images-amazon.com/images/I/51rmwZQM9GL._AC_US160_.jpg'),
(6, 9, 'Gandhi', 1982, 'PG', '15', 'This acclaimed biographical drama presents major events in the life of Mohandas Gandhi (Ben Kingsley), the beloved Indian leader who stood against British rule over his country. Dedicated to the concept of nonviolent resistance, Gandhi is initially dismissed by English officials, including the influential Lord Irwin (John Gielgud), but eventually he and his cause become internationally renowned, and his gatherings of passive protest move India towards independence.', 'https://images-na.ssl-images-amazon.com/images/I/51gpbF7DOrL._AC_US160_.jpg'),
(7, 6, 'Gladiator', 2000, 'R', '18', 'Commodus (Joaquin Phoenix) takes power and strips rank from Maximus (Russell Crowe), one of the favored generals of his predecessor and father, Emperor Marcus Aurelius, the great stoical philosopher. Maximus is then relegated to fighting to the death in the gladiator arenas.', 'https://images-na.ssl-images-amazon.com/images/I/51tdZ4ty0tL._AC_US160_.jpg'),
(8, 6, 'Bourne Identity', 2002, 'PG', '20', 'The story of a man (Matt Damon), salvaged, near death, from the ocean by an Italian fishing boat. When he recuperates, the man suffers from total amnesia, without identity or background... except for a range of extraordinary talents in fighting, linguistic skills and self-defense that speak of a dangerous past. He sets out on a desperate search-assisted by the initially rebellious Marie (Franka Potente) - to discover who he really is, and why he''s being lethally pursued by assassins.', 'https://images-na.ssl-images-amazon.com/images/I/51k2JulE7iL._AC_US160_.jpg'),
(9, 7, 'National Treasure', 2004, 'PG', '19', 'Historian and code-breaker Ben Gates (Nicolas Cage) has been searching his whole life for a rumored treasure dating back to the creation of the United States. Joining an expedition led by fellow treasure hunter Ian Howe (Sean Bean), Gates finds an ice-locked Colonial ship in the Arctic Circle that contains a clue linking the treasure to the Declaration of Independence. But when Howe betrays him, Gates has to race to get to the document ahead of his so-called colleague.', 'https://images-na.ssl-images-amazon.com/images/I/51g++CXZJRL._AC_US160_.jpg'),
(10, 9, 'Day One', 1989, 'PG', '13', 'Based on true events surrounding the creation of the atomic bomb, this drama follows the complicated relationship between physicist Leo Szilard (Michael Tucker), scientist J. Robert Oppenheimer (David Strathairn) and Gen. Leslie Groves (Brian Dennehy). Assigned to oversee the project, Groves chooses Oppenheimer to build the historic bomb. But, when World War II inspires the government to use the weapon, Szilard reconsiders his opinions about atomic warfare.', 'https://images-na.ssl-images-amazon.com/images/I/512xi2edRZL._AC_US160_.jpg'),
(11, 5, 'Everest', 1996, 'NR', '10', 'Everest is a 70mm American documentary film, from MacGillivray Freeman Films, about the struggles involved in climbing Mount Everest, the highest mountain peak on Earth, located in the Himalayan region of Nepal. It was released to IMAX theaters in March 1998 and became the highest-grossing film made in the IMAX format.', 'https://images-na.ssl-images-amazon.com/images/I/51SksRBmy+L._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(12, 7, 'Seven Years in Tibet', 1997, 'PG', '14', 'Typically impressive natural vistas from director Jean-Jacques Annaud (some secretly filmed on location in Tibet) highlight this adaptation of the memoir by Heinrich Harrer. Brad Pitt stars as the arrogant Heinrich, a famed Austrian mountain climber who leaves behind his wife and infant son to head a Himalayan expedition in 1939, only to fall into the hands of Allied forces as a prisoner of war. He and a fellow escapee, Peter Aufschnaiter (David Thewlis), make their way to the Forbidden City in Tibet, where Peter finds a wife and Heinrich befriends the Western culture-obsessed teenage Dalai Lama (Jamyang Jamtsho Wangchuk), the spiritual leader of his Buddhist nation. As Heinrich waits out the war, his friendship with the Dalai Lama begins to transform him from haughty to humble, but a crisis with China looms. A controversy over the revelation of the real-life Harrer''s Nazi Party affiliation brewed during the film''s production, forcing Annaud to briefly deal with the subject in the film. ~ Karl Williams, Rovi', 'https://images-na.ssl-images-amazon.com/images/I/51K4H3A813L._AC_US160_.jpg'),
(13, 6, 'Last of the Mohicans', 1992, 'R', '18', 'The last members of a dying Native American tribe, the Mohicans -- Uncas (Eric Schweig), his father Chingachgook (Russell Means), and his adopted half-white brother Hawkeye (Daniel Day-Lewis) -- live in peace alongside British colonists. But when the daughters (Madeleine Stowe, Jodhi May) of a British colonel are kidnapped by a traitorous scout, Hawkeye and Uncas must rescue them in the crossfire of a gruesome military conflict of which they wanted no part: the French and Indian War.', 'https://www.amazon.com/Last-Mohicans-Directors-Definitive-Cut/dp/B009CPJ9OM/ref=sr_1_1?s=movies-tv&ie=UTF8&qid=1469810992&sr=1-1&keywords=last+of+the+mohicans'),
(14, 7, 'Master and Commander', 2003, 'PG', '13', 'In 1805, aboard the H.M.S. Surprise, the brash Captain Jack Aubrey (Russell Crowe) and his trusted friend, the ship''s scholarly surgeon, Stephen Maturin (Paul Bettany), are ordered to hunt down and capture a powerful French vessel off the South American coast. Though Napoleon is winning the war and the men and their crew face an onslaught of obstacles, including their own internal battles, "Lucky Jack" is determined that nothing will stop the Surprise from completing its mission.', 'https://images-na.ssl-images-amazon.com/images/I/51Ymo0TjpDL._AC_US160_.jpg'),
(15, 10, 'Pride and Prejudice', 2005, 'PG', '17', 'In this adaptation of Jane Austen''s beloved novel, Elizabeth Bennet (Keira Knightley) lives with her mother, father and sisters in the English countryside. As the eldest, she faces mounting pressure from her parents to marry. When the outspoken Elizabeth is introduced to the handsome and upper-class Mr. Darcy (Matthew MacFadyen), sparks fly. Although there is obvious chemistry between the two, Darcy''s overly reserved nature threatens the fledgling relationship.', 'https://images-na.ssl-images-amazon.com/images/I/515Ze8T5jWL._AC_US160_.jpg'),
(16, 10, 'Notting Hill', 1999, 'PG', '16', 'William Thacker (Hugh Grant) is a London bookstore owner whose humdrum existence is thrown into romantic turmoil when famous American actress Anna Scott (Julia Roberts) appears in his shop. A chance encounter over spilled orange juice leads to a kiss that blossoms into a full-blown affair. As the average bloke and glamorous movie star draw closer and closer together, they struggle to reconcile their radically different lifestyles in the name of love.', 'https://images-na.ssl-images-amazon.com/images/I/51dBlYSvcgL._AC_US160_.jpg'),
(17, 10, 'Message in a Bottle', 1999, 'PG', '9', 'During her morning jog on the beach, journalist Theresa Osborne (Robin Wright Penn) discovers a bottle protruding from the sand. Inside it, she finds a heartbreaking, anonymous love letter. After her paper publishes the letter, Osborne tracks down the letter''s reclusive author, world-weary widower Garret Blake (Kevin Costner), in the Carolinas. But, as Osborne finds herself falling hopelessly in love with Blake, she becomes wracked with guilt over the real impetus for her visit.', 'https://images-na.ssl-images-amazon.com/images/I/51b8YxwlVDL._AC_US160_.jpg'),
(18, 4, 'Genesis Revisited', 2014, 'NR', '25', 'Steve Hackett covers old Genesis art rock classics at the Royal Albert Hall in London', 'https://images-na.ssl-images-amazon.com/images/I/61w2yb2uFgL._AC_US160_.jpg'),
(19, 7, 'The Count of Monte Cristo', 2002, 'PG', '12', 'The classic story of an innocent man wrongly, but deliberately imprisoned and his brilliant strategy for revenge against those who betrayed him. Dashing young sailor Edmond Dantes (Jim Caviezel) is a guileless and honest young man whose peaceful life and plans to marry the beautiful Mercedes (Dagmara Dominczyk) are abruptly shattered when his best friend Fernand (Guy Pearce), who wants Mercedes for himself, deceives him.', 'https://images-na.ssl-images-amazon.com/images/I/41AbugXl6YL._AC_US160_.jpg'),
(20, 8, 'Alien', 1979, 'R', '12', 'In deep space, the crew of the commercial starship Nostromo is awakened from their cryo-sleep capsules halfway through their journey home to investigate a distress call from an alien vessel. The terror begins when the crew encounters a nest of eggs inside the alien ship. An organism from inside an egg leaps out and attaches itself to one of the crew, causing him to fall into a coma.', 'https://images-na.ssl-images-amazon.com/images/I/41yNRJg0knL._AC_US160_.jpg'),
(21, 1, 'To Kill a Mockingbird', 1962, 'NR', '11', 'To Kill a Mockingbird Summary. To Kill a Mockingbird takes place in Alabama during the Depression, and is narrated by the main character, a little girl named Jean Louise "Scout" Finch. Her father, Atticus Finch, is a lawyer with high moral standards.', 'https://images-na.ssl-images-amazon.com/images/I/51ydPWzleGL._AC_US160_.jpg'),
(22, 6, 'The Hunt for Red October', 1990, 'PG', '20', 'Based on the popular Tom Clancy novel, this suspenseful movie tracks Soviet submarine captain Marko Ramius (Sean Connery) as he abandons his orders and heads for the east coast of the United States. Equipped with innovative stealth technology, Ramius'' submarine, "Red October," is virtually invisible. However, when an American sub briefly detects the Russians'' presence, CIA agent Jack Ryan (Alec Baldwin) sets out to determine Ramius'' motives, fearing he may launch an attack on the U.S.', 'https://images-na.ssl-images-amazon.com/images/I/41vRHUl6v9L._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(23, 9, 'Bridge on the River Kwai', 1957, 'PG', '12', 'Adaptation of the Pierre Bouelle novel about POWs in Burma forced to build a bridge to aid the war effort of their Japanese captors. British and American officers plot to blow up the structure, but the commander of the bridge''s construction has different plans.', 'https://images-na.ssl-images-amazon.com/images/I/51dEE9oKfVL._AC_US160_.jpg'),
(24, 9, 'Lawrence of Arabia', 1962, 'PG', '25', 'Due to his knowledge of the native Bedouin tribes, British Lieutenant T.E. Lawrence (Peter O''Toole) is sent to Arabia to find Prince Faisal (Alec Guinness) and serve as a liaison between the Arabs and the British in their fight against the Turks. With the aid of native Sherif Ali (Omar Sharif), Lawrence rebels against the orders of his superior officer and strikes out on a daring camel journey across the harsh desert to attack a well-guarded Turkish port.', 'https://images-na.ssl-images-amazon.com/images/I/51RC2btMlgL._AC_US160_.jpg'),
(25, 4, 'Secret World', 2003, 'NR', '19', 'A Concert Movie by Peter Gabriel - an original member of the British rock group Genesis', 'https://images-na.ssl-images-amazon.com/images/I/51pbYWwoveL._AC_US160_.jpg'),
(26, 4, 'Growing Up Live', 2002, 'NR', '17', 'A Concert Movie by Peter Gabriel filmed in Italy', 'https://images-na.ssl-images-amazon.com/images/I/51LLCIIsxPL._AC_US160_.jpg'),
(27, 3, 'For Love of the Game', 1999, 'PG', '14', 'Forty-year-old pitcher Billy Chapel (Kevin Costner) is practically a dinosaur by professional baseball standards, fast approaching the end of his career. But, as Chapel stands on the mound pitching the game of his life, his thoughts don''t turn to his prized history in sports, but rather return again and again to his tumultuous relationship with Jane Aubrey (Kelly Preston), a single mom who has stood at his side through the good and the bad but is now on the verge of leaving him.', 'https://images-na.ssl-images-amazon.com/images/I/419DGGAT54L._AC_US160_.jpg'),
(28, 3, 'Field of Dreams', 1989, 'PG', '15', 'When Iowa farmer Ray (Kevin Costner) hears a mysterious voice one night in his cornfield saying "If you build it, he will come," he feels the need to act. Despite taunts of lunacy, Ray builds a baseball diamond on his land, supported by his wife, Annie (Amy Madigan). Afterward, the ghosts of great players start emerging from the crops to play ball, led by "Shoeless" Joe Jackson. But, as Ray learns, this field of dreams is about much more than bringing former baseball greats out to play.', 'https://images-na.ssl-images-amazon.com/images/I/517zt7b3q5L._AC_US160_.jpg'),
(29, 2, 'Mash Season 1', 1973, 'G', '12', 'The 4077th Mobile Army Surgical Hospital is stuck in the middle of the Korean war. With little help from the circumstances they find themselves in, they are forced to make their own fun. Fond of practical jokes and revenge, the doctors, nurses, administrators, and soldiers often find ways of making wartime life bearable. Nevertheless, the war goes on, ', 'https://images-na.ssl-images-amazon.com/images/I/51o6j2pFBNL._AC_US160_.jpg'),
(30, 2, 'Mash Season 2', 1974, 'G', '12', 'The 4077th Mobile Army Surgical Hospital is stuck in the middle of the Korean war. With little help from the circumstances they find themselves in, they are forced to make their own fun. Fond of practical jokes and revenge, the doctors, nurses, administrators, and soldiers often find ways of making wartime life bearable. Nevertheless, the war goes on, ', 'https://images-na.ssl-images-amazon.com/images/I/51q9vvy7V2L._AC_US160_.jpg'),
(31, 1, 'Goodfellas', 1990, 'R', '17', 'Based on the bestselling biography, Henry Hill is a small time gangster, who takes part in a violent robbery with two ambitious gangsters. ', 'https://images-na.ssl-images-amazon.com/images/I/41hSe0+BbRL._AC_US160_.jpg'),
(32, 1, 'The Patriot', 2000, 'R', '16', 'A reluctant South Carolina farmer (Mel Gibson) is forced to fight the British in this epic adventure of the American Revolution. Directed by Roland Emmerich (Independence Day). Screenplay by Robert Rodat (Saving Private Ryan). ', 'https://images-na.ssl-images-amazon.com/images/I/41qBsS+BNXL._AC_US160_.jpg'),
(33, 1, 'Amistad', 1997, 'R', '14', 'AMISTAD is about a 1839 mutiny aboard a slave ship that is traveling towards the Northeast Coast of America. Much of the story involves a court-room drama about the free-man who led the revolt. ', 'https://images-na.ssl-images-amazon.com/images/I/51tI6cN6IcL._AC_US160_.jpg'),
(34, 1, 'Born on the Fourth of July', 1989, 'R', '15', 'The biography of Ron Kovic. Paralyzed in the Vietnam war, he becomes an anti-war and pro-human rights political activist after feeling betrayed by the country he fought for. ', 'https://images-na.ssl-images-amazon.com/images/I/519511NjLOL._AC_US160_.jpg'),
(35, 1, 'Forrest Gump', 1994, 'PG', '12', 'Tom Hanks gives an astonishing performance as Forrest, an everyman whose simple innocence comes to embody a generation. ', 'https://images-na.ssl-images-amazon.com/images/I/41ndysjF9TL._AC_US160_.jpg'),
(36, 1, 'Ordinary People', 1980, 'PG', '12', 'Ordinary People is an intense examination of a family being torn apart by tension and tragedy. Donald Sutherland and Mary Tyler Moore star as the upper-middle-class couple whose "ordinary" existence is irrevocably shattered by the death of their oldest son in a boating accident. ', 'https://images-na.ssl-images-amazon.com/images/I/51rPLCr+eTL._AC_US160_.jpg'),
(37, 1, 'The Age of Innocence', 1993, 'PG', '13', 'Daniel Day-Lewis and Michelle Pfeiffer star in a ravishing romance about three wealthy New Yorkers caught in a tragic love triangle. ', 'https://images-na.ssl-images-amazon.com/images/I/51c2lcBMExL._AC_US160_.jpg'),
(38, 1, 'The Godfather Part I', 1972, 'R', '16', 'Director Coppola paints a chilling portrait of the Sicilian clan''s rise and near fall from power in America, masterfully balancing the story between the Corleone''s family life and the ugly crime business in which they are engaged. ', 'https://images-na.ssl-images-amazon.com/images/I/41O9BsdpBnL._AC_US160_.jpg'),
(39, 1, 'The Godfather Part II', 1974, 'R', '17', 'The continuing saga of the Corleone crime family tells the story of a young Vito Corleone growing up in Sicily and in 1910s New York; and follows Michael Corleone in the 1950s as he attempts to expand the family business into Las Vegas, Hollywood and Cuba. ', 'https://images-na.ssl-images-amazon.com/images/I/51hIWxA0tML._AC_US160_.jpg'),
(40, 2, 'Its a Mad Mad Mad World', 2004, 'PG', '11', 'The story begins during a massive traffic jam, caused by reckless driver Smiler Grogan (Jimmy Durante), who, before kicking the bucket, cryptically tells the assembled drivers that he''s buried a fortune in stolen loot, under the Big W. All of the motorists set out to find the fortune.', 'https://images-na.ssl-images-amazon.com/images/I/51+UyW4NuzL._AC_US160_.jpg'),
(41, 2, 'Airplane', 1980, 'PG', '16', 'The persons and events in this film are fictitious - fortunately! A masterpiece of off-the-wall comedy, Airplane! ', 'https://images-na.ssl-images-amazon.com/images/I/41TdD2fjCZL._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(42, 2, 'Caddyshack', 1980, 'PG', '12', 'A comedy about a construction tycoon who tries to join a snobby country club that doesn''t want him as a member. ', 'https://images-na.ssl-images-amazon.com/images/I/51I2FnXiF+L._AC_US160_.jpg'),
(43, 2, 'Meatballs', 1979, 'PG', '10', 'Bill Murray is at his hilarious best in this classic comedy that''s "Animal House goes to summer camp" (Newsweek). Murray plays Tripper, the wisecracking, rule-bending head counselor at Camp North Star. Whether playing pranks on Camp North Star''s clueless director, wooing a female counselor, or scheming against the rich brats of a rival camp, Tripper delivers fun and mayhem. ', 'https://images-na.ssl-images-amazon.com/images/I/51iUEQ1gX5L._AC_US160_.jpg'),
(44, 2, 'Cheers Season 1', 1982, 'NR', '11', 'Bartender Sam Malone (Ted Danson) and the object of his unrequited love, Diane (Shelley Long), cross swords in hilarious episodes from the landmark television comedy. Joining them for the fun in one of the most popular television series ever are Norm, Cliff, Carla, Frasier and "Coach." ', 'https://images-na.ssl-images-amazon.com/images/I/51AA74VC0CL._AC_US160_.jpg'),
(45, 2, 'Threes Company Season 1', 2003, 'NR', '14', 'Janet and Chrissy get Jack as a roommate for their Santa Monica apartment. Jack can cook (he''s studying to be a chef) and, when called to do so, pretends he''s gay to legitimize the arrangement. ... But their landlord Mr. Roper doesn''t agree until he is told that Jack''s gay.', 'https://images-na.ssl-images-amazon.com/images/I/5173P+I+kNL._AC_US160_.jpg'),
(46, 2, 'Three Amigos', 1986, 'PG', '14', 'Three cowboy movie stars from the silent era -- Dusty Bottoms (Chevy Chase), Lucky Day (Steve Martin) and Ned Nederlander (Martin Short) -- are fired when one of their movies bombs. In what seems to be a career-saving offer, young Mexican woman Carmen (Patrice Martinez) offers them a high-paying gig in her village. The three jump at the opportunity, expecting to do their typical act, but Carmen believes they are really heroes and asks them to rid her village of bad guy El Guapo (Alfonso Arau).', 'https://images-na.ssl-images-amazon.com/images/I/51SFYJTgODL._AC_US160_.jpg'),
(47, 3, 'Moneyball', 2011, 'PG', '14', 'Brad Pitt stars in this film about Oakland A''s general manager Billy Beane and his attempt to put together a baseball club on a budget by employing computer-generated analysis to draft his players. ', 'https://images-na.ssl-images-amazon.com/images/I/41hV6kKzPvL._AC_US160_.jpg'),
(48, 3, 'Ali', 2001, 'R', '16', 'Will Smith puts on the gloves and steps between the ropes as "Ali," arguably the most facinating personality in sports history in this biopic from Academy Award nominated director Michael Mann. ', 'https://images-na.ssl-images-amazon.com/images/I/51a469rFbpL._AC_US160_.jpg'),
(49, 3, 'Tin Cup', 1996, 'PG', '13', 'If a golfing instructor would''ve played it safe, he would not havefallen in love with his latest student, Molly. Now he has to win theU.S. Open to win her heart. ', 'https://images-na.ssl-images-amazon.com/images/I/51IB9K1kV-L._AC_US160_.jpg'),
(50, 3, 'The Natural', 1984, 'PG', '18', 'Robert Redford stars in the inspiring fable of a baseball player''s major league dreams and the mysterious woman who shatters them. ', 'https://images-na.ssl-images-amazon.com/images/I/51aQ2El-kLL._AC_US160_.jpg'),
(51, 3, 'The Rookie', 2002, 'PG', '15', 'A baseball coach makes the major league after making a bet. ', 'https://images-na.ssl-images-amazon.com/images/I/51aMExWfTKL._AC_US160_.jpg'),
(52, 3, 'Brians Song', 1971, 'PG', '11', 'James Caan and Billy Dee Williams star in the true story of Chicago Bears'' football players Brian Piccolo and Gale Sayers. ', 'https://images-na.ssl-images-amazon.com/images/I/51DIohVPpwL._AC_US160_.jpg'),
(53, 3, 'Slapshot', 1977, 'R', '13', 'Paul Newman is the coach of the Chiefs, a third-rate, minor league hockey team. To build up attendance at their games, management signs up three odd-looking players whose job it is to literally attack and demolish opposition to the delight and cheers of a steadily increasing throng of fans. ', 'https://images-na.ssl-images-amazon.com/images/I/51rW6l4yZxL._AC_US160_.jpg'),
(54, 3, 'Chariots of Fire', 1981, 'PG', '12', 'An inspirational look at the competitive spirit, featuring two runners competing for Olympic glory in their own fashion and for their own separate reasons. ', 'https://images-na.ssl-images-amazon.com/images/I/51MGP01nVKL._AC_US160_.jpg'),
(55, 4, 'Purple Rain', 1984, 'PG', '17', 'Set against the subculture of the thriving Minneapolis music scene, a struggling musician dealing with his hatred for his abusive father and his love for a beautiful singer/dancer. ', 'https://images-na.ssl-images-amazon.com/images/I/51qNLH2R-OL._AC_US160_.jpg'),
(56, 4, 'Bring on the Night', 1985, 'NR', '19', 'A documentary about the making of the first Sting album.', 'https://images-na.ssl-images-amazon.com/images/I/51oPBwH7sLL._AC_US160_.jpg'),
(57, 4, 'Godspell', 1973, 'NR', '11', 'The long-running ''70s stage musical - based on the "Godspell According to St. Matthew" - comes to DVD in this exhilarating big-screen adaption. Includes the hit song Day By Day. ', 'https://images-na.ssl-images-amazon.com/images/I/51F0jUVOUUL._AC_US160_.jpg'),
(58, 4, 'Oliver', 1968, 'G', '10', 'Musical version of Charles Dickens'' "Oliver Twist" adapted from the stage hit, 1968 Best Picture Oscar(r). ', 'https://images-na.ssl-images-amazon.com/images/I/514vsMaqc5L._AC_US160_.jpg'),
(59, 4, 'Oklahoma', 2010, 'G', '14', 'Set in the Oklahoma Territory in the early 1900''s, this joyous celebration of frontier life is a story of tender romance and dangerous passion. Gordon MacRae is Curly, a sunny, good-natured ranch hand, and Shirley Jones is Laurey Williams, the farmer''s daughter he loves. Rod Steiger is he menacing Jud, who tries to comes between them. ', 'https://images-na.ssl-images-amazon.com/images/I/51xMZM6ZRkL._AC_US160_.jpg'),
(60, 4, 'Jesus Christ Superstar', 1973, 'NR', '15', 'See one of the world''s favorite musicals come to life as powerful performances from the cast make this version of Jesus Christ Superstar an unforgettable extravaganza you won''t want to miss! ', 'https://images-na.ssl-images-amazon.com/images/I/51WMfi-d7zL._AC_US160_.jpg'),
(61, 4, 'Les Miserables', 2012, 'PG', '17', 'Hugh Jackman, Oscar-winner Russell Crowe and Anne Hathaway star in the critically acclaimed adaptation of the epic musical phenomenon that is a timeless testament to the human spirit. ', 'https://images-na.ssl-images-amazon.com/images/I/51wPo0FUGyL._AC_US160_.jpg'),
(62, 5, 'Amy', 2015, 'NR', '14', 'From BAFTA award-winning director Asif Kapadia (Senna), AMY tells the incredible story of six-time Grammy-winner Amy Winehouse - in her own words. Featuring extensive unseen archive footage and previously unheard tracks, this strikingly modern, moving and vital film shines a light on the world we live in, in a way that very few can. ', 'https://images-na.ssl-images-amazon.com/images/I/41RZv2moydL._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(63, 5, 'After Braveheart', 2016, 'NR', '14', 'Ever wondered what happened after the epic events that are portrayed in the Hollywood movie Braveheart? A new docudrama reveals the untold story of how a Scottish army tried to drive the English out of Ireland 700 years ago. ', 'https://images-na.ssl-images-amazon.com/images/I/51N-HZ2+XwL._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(64, 5, 'Jon Benet Ramsey', 2014, 'NR', '12', 'Who Killed JonBenet Ramsey? A Michael Piehl Film. A newly released documentary detailing the facts in the JonBenet Ramsey murder. Never before seen or heard testimony and hand writing analysis. Lawyer, Darnay Hoffman deposes John and Patsy Ramsey in the first ever footage of them directly answering point blank questions about the death of their daughter. ', 'https://images-na.ssl-images-amazon.com/images/I/51W3YZl95CL._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(65, 5, 'Zero Days', 2016, 'NR', '14', ' A cyber attack launched by the U.S. and Israel on an Iranian nuclear facility ends up exposing our own vulnerabilities in this documentary thriller from Academy Award® winning filmmaker Alex Gibney (Going Clear). ', 'https://images-na.ssl-images-amazon.com/images/I/51yAibFr9wL._AC_US160_.jpg'),
(66, 5, 'Navy Seals', 1996, 'NR', '17', 'A revealing 4-part series about the elite group of American warriors called Navy SEALs. Filmed over 6 years, the collection includes, In Harm''s Way, Hellweek, Direct Action!, and The Silent Option, which won an Emmy Award. ', 'https://images-na.ssl-images-amazon.com/images/I/51c57v92amL._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(67, 5, 'Super Thief', 2013, 'NR', '13', 'A captivating firsthand look at the life of Phil Christopher, a career criminal, Mafia associate, and one of the most successful bank robbers in United States history ', 'https://images-na.ssl-images-amazon.com/images/I/51addMRQhLL._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(68, 5, 'Silent Conquest', 2015, 'PG', '15', 'The end of freedom of speech in the West. ', 'https://images-na.ssl-images-amazon.com/images/I/41OMmwIEIZL._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(69, 5, 'Sharks', 2014, 'PG', '14', 'The white shark, the hammerhead shark or the whale shark can all be seen in this breathtaking underwater adventure! ', 'https://images-na.ssl-images-amazon.com/images/I/61RvMLi2jXL._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(70, 5, 'Java in Jeopardy', 2016, 'NR', '10', 'In the past hundred years alone, it has claimed over 1,500 victims. The risk of another serious eruption is high and could possibly even have consequences which would be felt globally. Now scientists are looking for a thus far unknown tectonic disturbance, which might possibly prove the key to their research. ', 'https://images-na.ssl-images-amazon.com/images/I/51JeRRZtw6L._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(71, 6, 'Rambo', 1982, 'R', '16', 'When an Vietnam war vet tries to visit an old army buddy, the local cops arrest and abuse him. When he can''t escape his tormentors, he decides to fight back. ', 'https://images-na.ssl-images-amazon.com/images/I/61qaI9JuL0L._AC_US160_.jpg'),
(72, 6, 'Faster', 2010, 'R', '18', 'After 10 years in prison, Driver (Dwayne Johnson) is now a free man with a single focus - hunting down the people responsible for brutally murdering his brother. ', 'https://www.amazon.com/Faster-Dwayne-Johnson/dp/B004QJPF2O/ref=sr_1_10?s=movies-tv&ie=UTF8&qid=1469835422&sr=1-10&keywords=action+movies'),
(73, 6, 'EndGame', 1991, 'PG', '15', ' Every day the country is more ungovernable as it plunges towards the apocalypse of a race war. But continents away in a rural English manor house, secret talks between the two warring parties will change everything and achieve the unimaginable. ', 'https://images-na.ssl-images-amazon.com/images/I/51y74DJ4HEL._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(74, 6, 'The Mechanic', 2011, 'R', '19', 'Arthur Bishop is a ???mechanic?? ??? an elite assassin with a strict code and unique talent for cleanly eliminating targets. It??s a job that requires professional perfection and total detachment, and Bishop is the best in the business. But when his mentor and close friend Harry is murdered, Bishop is anything but detached. His next assignment is self-imposed ??? he wants those responsible dead. ', 'https://images-na.ssl-images-amazon.com/images/I/51lzcqHQGAL._AC_US160_.jpg'),
(75, 6, 'Wild Card', 2015, 'R', '14', 'Nick Wild (Jason Statham) is a Las Vegas bodyguard with lethal professional skills and a personal gambling problem. When his friend is beaten by a sadistic thug, Nick strikes back, only to find out the thug is the son of a powerful mob boss. ', 'https://images-na.ssl-images-amazon.com/images/I/51OL7L03l2L._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(76, 6, 'Ink', 2009, 'PG', '14', 'IT''S A WONDERFUL LIFE meets SIN CITY in this high-concept visual thriller. John and Emma, father and daughter, are thrust into a fantastical dream-world battle between forces of good and evil in this allegorical tale of love, loss and the search for redemption. ', 'https://images-na.ssl-images-amazon.com/images/I/51ZE0nWulUL._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(77, 7, 'Crosswinds', 2000, 'NR', '13', 'Trying to recover gold from a crashed plane in New Guinea, a captain encounters thieves and native head-hunters. ', 'https://images-na.ssl-images-amazon.com/images/I/51d1RiPbVLL._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(78, 7, 'Hawks', 2000, 'NR', '11', 'A poignant comedy-drama about two terminal cancer patients who decide not to spend their remaining time in a hospital ward. After sneaking out of the hospital and stealing an ambulance, they set off on an adventure. ', 'https://images-na.ssl-images-amazon.com/images/I/41fR7P3yK-L._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(79, 7, 'Somewhere West', 2016, 'NR', '13', 'A breathtaking road-film that explores the human spirit with emotional breadth and quiet subtlety. Ian, a terminally ill young man, forgoes treatment and journeys in search of a beautiful place to spend his final moments. ', 'https://images-na.ssl-images-amazon.com/images/I/510r-G2trML._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(80, 7, 'Deep Water', 2007, 'NR', '12', 'The remarkable, true story of the first solo, non-stop, round-the-world boat race and the psychological toll it took on its competitors. ', 'https://images-na.ssl-images-amazon.com/images/I/61RXBUqM5GL._AC_US160_.jpg'),
(81, 7, 'The Dove', 2000, 'PG', '11', 'The adventures of Robin Lee Graham, the sixteen-year-old yachtsman who makes a five-year voyage around the world. ', 'https://images-na.ssl-images-amazon.com/images/I/41NyPxbhhbL._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(82, 6, 'Roam', 2006, 'NR', '14', 'Roam is a mountain bike film that depicts the travels of some of the world''s top riders as they explore both new places to ride as well as visiting some of the notorious "meccas" of mountain biking. ', 'https://images-na.ssl-images-amazon.com/images/I/41f9xo96xCL._AC_US160_.jpg'),
(83, 8, 'Aliens', 1986, 'R', '17', 'Sigourney Weaver stars in Aliens, the sequel to the 1979 blockbuster Alien, reprising her role as Officer Ripley, the sole survivor of the spaceship Nostromo''s encounter with a deadly extraterrestrial. This time she returns to the very planet where her nightmare originally began with a squad of heavily armed marines, in a search-and-rescue mission for some missing space colonists. ', 'https://images-na.ssl-images-amazon.com/images/I/51JSYow67oL._AC_US160_.jpg'),
(84, 8, 'Star Wars', 1977, 'PG', '15', 'Young farm boy Luke Skywalker is thrust into a galaxy of adventure when he intercepts a distress call from the captive Princess Leia. The event launches him on a daring mission to rescue her from the clutches of Darth Vader and the Evil Empire. Purchase also includes bonus features, available to watch in Your Video Library. ', 'https://images-na.ssl-images-amazon.com/images/I/51iHtTvV6KL._AC_US160_.jpg'),
(85, 8, 'Star Trek IV', 1986, 'PG', '13', 'To save Earth from an alien probe, Kirk and his crew go back in time to retrieve the only beings who can communicate with it, humpback whales. ', 'https://images-na.ssl-images-amazon.com/images/I/513sCrsy3IL._AC_US160_.jpg'),
(86, 8, 'Star Trek II', 1982, 'PG', '16', 'Admiral Kirk''s midlife crisis is interrupted by the return of an old enemy looking for revenge and a potentially destructive device.', 'https://images-na.ssl-images-amazon.com/images/I/51XZZ5vetXL._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(87, 8, 'Star Wars 5', 1980, 'PG', '18', 'The Rebels scatter after the Empire attacks their base on the ice planet Hoth. Han Solo and Princess Leia are pursued by Imperials, while Luke trains with Jedi Master Yoda. Luke must battle Darth Vader and learns the shocking truth of his past. Purchase also includes bonus features, available to watch in Your Video Library. ', 'https://images-na.ssl-images-amazon.com/images/I/61dXCro7g1L._AC_US160_.jpg'),
(88, 8, 'Star Wars 6', 1983, 'PG', '13', 'The Empire prepares to crush the Rebellion with a more powerful Death Star. The Rebel fleet counters with a massive attack on the space station. Luke Skywalker confronts Darth Vader in a final climactic duel. Purchase also includes bonus features, available to watch in Your Video Library. ', 'https://images-na.ssl-images-amazon.com/images/I/51d-W0Ik57L._AC_US160_.jpg'),
(89, 8, 'Star Trek 6', 1991, 'PG', '19', 'The crews of the Enterprise and the Excelsior must stop a plot to prevent a peace treaty between the Klingon Empire and the Federation. ', 'https://images-na.ssl-images-amazon.com/images/I/51yLQ9m7EcL._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(90, 9, 'The Discoverers', 2014, 'PG', '12', 'Griffin Dunne leads an award-winning ensemble in this hilarious, heartfelt road movie about a family forced on a Lewis and Clark historical reenactment trek, who discover themselves and each other as they journey across America. ', 'https://images-na.ssl-images-amazon.com/images/I/61w4SRD2rCL._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(91, 9, 'Discovering Emma', 2011, 'PG', '17', 'The life of Emma Hale Smith, featuring interviews with noted LDS scholars and authors Susan Easton Black, Gracia Jones, and Paul Smith. ', 'https://images-na.ssl-images-amazon.com/images/I/51DfweT7xsL._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(92, 9, 'The Red Baron', 2008, 'NR', '10', 'Europe, 1916. Baron Manfred von Richthofen is, at the age of just 24, the crack pilot of the German aerial combat forces - a legend in his own time, a hero at home and a man both feared and respected by the enemy. But even for this living legend, each new combat mission could be his last... ', 'https://images-na.ssl-images-amazon.com/images/I/51dPLONRJFL._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(93, 9, 'The Admirer', 2016, 'NR', '14', 'Welcome to Russia to experience a poignant love story. With a blend of the idealistic and the impossible, the two leading characters of this movie will show you that love is worth every tireless effort. In Saint Petersburg, Chekhov meets aspiring writer Lydia Avilova. Between them arises a mutual sympathy, which develops into a deep feeling. But Avilova is married, and Chekhov is terminally ill. ', 'https://images-na.ssl-images-amazon.com/images/I/51OGpilDh3L._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(94, 10, 'Pretty Woman', 1990, 'PG', '13', 'A classic rags-to-riches love story. ', 'https://images-na.ssl-images-amazon.com/images/I/41sizefwQBL._AC_US160_.jpg'),
(95, 10, 'About Time', 2013, 'PG', '11', 'From the director of Love Actually comes this heartwarming comedy about love and time travel starring Rachel McAdams that critics are calling "definitely one to watch over and over again." ', 'https://images-na.ssl-images-amazon.com/images/I/51KOqeXvWVL._AC_US160_.jpg'),
(96, 10, 'At First Sight', 2013, 'NR', '17', 'A story of a young woman architect who falls in love with a blind man. She encourages him to undergo a radical operation to restore his sight, but ultimately his truest vision comes from the love he finds in his heart. ', 'https://images-na.ssl-images-amazon.com/images/I/51j0teYHLML._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(97, 10, 'The Lucky One', 2012, 'PG', '13', 'U.S. Marine Sergeant Logan Thibault returns from his third tour of duty in Iraq, with the one thing he credits with keeping him alive-a photograph of a woman he doesn''t even know. ', 'https://images-na.ssl-images-amazon.com/images/I/518jLr8mBxL._AC_US160_.jpg'),
(98, 10, 'If I Stay', 2014, 'PG', '19', 'A chronicle of a fatal car accident involving 17-year-old musician Mia and her boyfriend. ', 'https://images-na.ssl-images-amazon.com/images/I/51rbwfgFPML._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(99, 10, 'Belle and the Beast', 2011, 'PG', '11', 'This classic fairytale comes to life in modern times to capture your heart. ', 'https://images-na.ssl-images-amazon.com/images/I/51LktOkSyaL._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg'),
(100, 10, 'The Age of Adaline', 2015, 'NR', '12', 'Blake Lively and Harrison Ford star in this stirring romantic drama about a 29-year-old woman who has stopped aging - and the timeless power of love. ', 'https://images-na.ssl-images-amazon.com/images/I/51JK64XWsjL._PI_PJStripe-Prime-Only-500px,TopLeft,0,0_AC_US160_.jpg');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
